---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hack-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hack-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: hack-sa
  namespace: hack
  
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: k8ctl
  name: k8ctl
spec:
  serviceAccountName: hack-sa
  containers:
  - image: bitnami/kubectl:latest
    name: k8ctl
    command: [ "sleep" ]
    args: [ "infinity" ]
    
  
